user_input = input("Enter Inicial String: ")

print("A apppears ",user_input.lower().count("a"), " Times")
print("B apppears ",user_input.lower().count("b"), " Times")
print("C apppears ",user_input.lower().count("c"), " Times")
print("D apppears ",user_input.lower().count("d"), " Times")
print("E apppears ",user_input.lower().count("e"), " Times")
print("F apppears ",user_input.lower().count("f"), " Times")
print("G apppears ",user_input.lower().count("g"), " Times")
print("H apppears ",user_input.lower().count("h"), " Times")
print("I apppears ",user_input.lower().count("i"), " Times")
print("J apppears ",user_input.lower().count("j"), " Times")
print("K apppears ",user_input.lower().count("k"), " Times")
print("L apppears ",user_input.lower().count("l"), " Times")
print("M apppears ",user_input.lower().count("m"), " Times")
print("N apppears ",user_input.lower().count("n"), " Times")
print("O apppears ",user_input.lower().count("o"), " Times")
print("P apppears ",user_input.lower().count("p"), " Times")
print("Q apppears ",user_input.lower().count("q"), " Times")
print("R apppears ",user_input.lower().count("r"), " Times")
print("S apppears ",user_input.lower().count("s"), " Times")
print("T apppears ",user_input.lower().count("t"), " Times")
print("U apppears ",user_input.lower().count("u"), " Times")
print("V apppears ",user_input.lower().count("v"), " Times")
print("W apppears ",user_input.lower().count("w"), " Times")
print("X apppears ",user_input.lower().count("x"), " Times")
print("Y apppears ",user_input.lower().count("y"), " Times")
print("Z apppears ",user_input.lower().count("z"), " Times")