# Generated by Django 4.2 on 2026-06-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the doctor', max_length=100)),
                ('specialization', models.CharField(help_text='Medical specialization (e.g., Cardiologist, Dentist)', max_length=100)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('phone', models.CharField(help_text='Contact phone number', max_length=15)),
                ('email', models.EmailField(help_text='Unique email address for contact', max_length=254, unique=True)),
            ],
        ),
    ]
